### ISSUE TITLE
Error in generating openapi client with openapi-generator to typescript-fetch

### ISSUE THREAD

**Issue by l1xiangyi** [openai/openai-openapi#133]
openapi-generator-cli generate -i src/openapi.yaml -g typescript-fetch -o src/openai-client

Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 5, Warning count: 0
Errors: 
        -attribute components.schemas.CreateFineTuneRequest.default is not of type `array`
        -attribute components.schemas.CreateAnswerRequest.default is not of type `object`
        -attribute components.schemas.CreateCompletionRequest.default is not of type `object`
        -attribute components.schemas.CreateChatCompletionRequest.default is not of type `object`
        -attribute components.schemas.CreateClassificationRequest.default is not of type `object`

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:684)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:711)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:511)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

**Comment by 2catycm** [comment]
My errror log is like this:
```bash
# Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
#  | Error count: 2, Warning count: 10
# Errors:
#         -attribute components.schemas.CreateCompletionRequest.default is not of type `object`
#         -attribute components.schemas.CreateChatCompletionRequest.default is not of type `object`
# Warnings:
#         -attribute components.schemas.CreateCompletionRequest.default is not of type `object`
#         -attribute components.schemas.CreateChatCompletionRequest.default is not of type `object`

#         at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:701)
#         at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:728)
#         at org.openapitools.codegen.cmd.Generate.execute(Generate.java:519)
#         at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
#         at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Comment by 2catycm** [comment]
But I am confused, it seems in the yaml components.schemas.CreateCompletionRequest
we didn't define the default value for this schema
I am not familar with OpenAPI format,
is the default automatically built upon its sub properties' default value? 
If yes, then why isn't it an object? Is it a bug to [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator)?

**Comment by 2catycm** [comment]
I seee this https://stackoverflow.com/questions/58991883/jsonschema-xxx-is-not-of-type-object
 it seems the error indicated it actually not the problem. It is not because the type is not object, but because the object don't have required field

**Comment by 2catycm** [comment]
After some exploration，I figure out the root cause of this error.
It is on "model" definition, the OpenAPI generator doesn't support something like this: 
![image](https://github.com/openai/openai-openapi/assets/41530341/32d7155d-c6ea-4f2f-acc3-c5acc237c43f)

This definition is bad. 
It wants it to be an enum, it also want to support arbitary model name, making it "anyof" union.
however that is not recognized

**Comment by 2catycm** [comment]
Two kinds of solution here,
1. type:string and examples are the enum
2. is there a "enum" type for json schema? I am not familar with js
3. Is anyof generally not supported? Or just breaks for “str or str”

**Comment by 2catycm** [comment]
> Two kinds of solution here,
> 
> 1. type:string and examples are the enum
> 2. is there a "enum" type for json schema? I am not familar with js
> 3. Is anyof generally not supported? Or just breaks for “str or str”

For 1., it seems there is only a "default" and "example", no "examples" in OpenAPI Spec, right?
I cannot figure out when to use "default" and when to use "example", they are so alike.

**Comment by 2catycm** [comment]
But is should have "examples", how can example be single?
enum is restrictions, not extensible? or many "enum" is what I think to be examples and extensible?

**Comment by 2catycm** [comment]
> enum

I believe this is the cause because the generated python\java\rust code cannot well define the class "CreateChatCompletionRequestModel"
they treat is as an attribute of class "CreateChatCompletionRequest" and it is an empty class with nothing.

and the json deserializer doesn't work for "CreateChatCompletionRequestModel" since it is not well defined as string, but an empty struct.

**Comment by 2catycm** [comment]
I am confused with the document of OpenAPI 3.0 https://swagger.io/specification/

It seems neither "example"
 nor "default" are valid keyword of the OpenAPI 3.0 schema dialect

**Comment by judithgull** [comment]
The errors
> #         -attribute components.schemas.CreateCompletionRequest.default is not of type `object`
> #         -attribute components.schemas.CreateChatCompletionRequest.default is not of type `object`

disappear for me, if I comment the default in logit_bias for both objects 

logit_bias:
          type: object
          x-oaiTypeLabel: map
          #default: null

**Comment by scayze** [comment]
> The errors -attribute components.schemas.CreateCompletionRequest.default is not of type `object` -attribute components.schemas.CreateChatCompletionRequest.default is not of type `object`
> 
> disappear for me, if I comment the default in logit_bias for both objects
> 
> logit_bias: type: object x-oaiTypeLabel: map #default: null

Had the same issue, can confirm that this solution works. Thanks for the workaround!

**Comment by jbeckwith-oai** [comment]
Thank you for reporting this, and thanks as well to everyone who reproduced the problem and narrowed the older failure down to the nullable `logit_bias` defaults.

I rechecked the report against the current specification on `main` (`db3e531`, OpenAPI 3.1):

- `CreateFineTuneRequest`, `CreateAnswerRequest`, and `CreateClassificationRequest` are no longer present in the current specification.
- `CreateCompletionRequest` and `CreateChatCompletionRequest` no longer define the component-level defaults named in the validation errors.
- I also ran OpenAPI Generator 7.23's validator against the current `openapi.yaml`. It does not report any of the five `default is not of type` errors from this issue. (It currently reports unrelated validation findings involving newer beta extensions, which are separate from this report.)

The discussion here was particularly helpful in documenting how older OpenAPI Generator versions attributed nested nullable defaults to the enclosing object. That exact failure has since been overtaken by both the specification and generator changes, so I’m closing this as resolved/obsolete.

If a current OpenAPI Generator release still fails specifically on `CreateCompletionRequest` or `CreateChatCompletionRequest`, please open a new issue with the generator version, command, and current validation output so we can investigate the modern schema independently. Thanks again for the detailed report and follow-up investigation.
