### ISSUE TITLE
Java code generation fails with org.openapitools.codegen.SpecValidationException

### ISSUE THREAD

**Issue by relango** [openai/openai-openapi#14]
I am trying to build a Java SDK by autogenerating code using open API code generator, but running into problems.

When I ran the command `openapi-generator generate -i openapi.yaml -g java`

I am getting this exception:

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 4, Warning count: 0
Errors:
	-attribute components.schemas.CreateFineTuneRequest.default is not of type `array`
	-attribute components.schemas.CreateAnswerRequest.default is not of type `object`
	-attribute components.schemas.CreateCompletionRequest.default is not of type `object`
	-attribute components.schemas.CreateClassificationRequest.default is not of type `object`

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:604)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

When Run with `--skip-validate-spec` flag, the code generation works, but generated code fails to compile. Looks like there are some issues with schema. Can we get this fixed?

**Comment by Netizine** [comment]
I made a few corrections to the openai yaml and was able to create an angular typescript library. I got the same errors (Theres 5 if you use the latest openai spec. I pasted it as a gist here. https://gist.github.com/Netizine/48809371b37669800affda391192c214. Should work for you as it uses the same engine

**Comment by Jmfwolf** [comment]
@relango hey try using the one I generated from my fork
https://github.com/Jmfwolf/openai-openapi/tree/java-sdk/openai-java

**Comment by logankilpatrick** [comment]
We have made a ton of API changes recently but please open a new issue if you are still having issues.

**Comment by 2catycm** [comment]
How did you fix that? What is the root of the issue? Can you give me some hint?
